spring:
  application:
    name: Manage-Http-Session-With-Redis

  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379